services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:3000"
    mem_limit: 256m
    cpus: 0.9
    volumes:
      - /home/opc/docker-stats.log:/app/docker-stats.log:ro
      - /home/opc/gol-data:/app/data
      - /home/opc/host-stats.json:/app/host-stats.json:ro